const ANIMAL_COMPANIONS = [
  {id:'ape', n:'Ape', size:'Small', hp:8, m:[3,1,2,-4,2,0], skill:'Intimidation', senses:'Low-light vision', speed:'25 ft, climb 25 ft',
    atk:[['Fist','1d8','B',[]]], support:'Creatures you hit and damage in its reach become frightened 1.', man:'Frightening Display', s:'Player Core'},
  {id:'arboreal-sapling', n:'Arboreal Sapling', r:1, size:'Small', hp:8, m:[3,1,2,-4,2,0], skill:'Stealth', senses:'Low-light vision', speed:'25 ft',
    atk:[['Branch','1d8','B',[]]], support:'After you damage a foe in its reach, the next square the foe moves into is difficult terrain.', man:'Throw Rock',
    note:'Usually only for druids in both the animal and leaf orders.', s:'Player Core'},
  {id:'badger', n:'Badger', size:'Small', hp:8, m:[2,2,2,-4,2,0], skill:'Survival', senses:'Low-light vision, scent (imprecise, 30 ft)', speed:'25 ft, burrow 10 ft, climb 10 ft',
    atk:[['Jaws','1d8','P',[]],['Claw','1d6','S',['agile']]], support:'Foes you hit and damage in its reach can’t Step until they move from their position.', man:'Badger Rage', s:'Player Core'},
  {id:'bat', n:'Bat', size:'Small', hp:6, m:[2,3,2,-4,1,0], skill:'Stealth', senses:'Echolocation 20 ft, low-light vision', speed:'15 ft, fly 30 ft',
    atk:[['Jaws','1d6','P',['finesse']],['Wing','1d4','S',['agile','finesse']]], support:'Foes you damage in its reach take −1 to attack rolls.', man:'Wing Thrash', s:'Player Core'},
  {id:'bear', n:'Bear', size:'Small', hp:8, m:[3,2,2,-4,1,0], skill:'Intimidation', senses:'Low-light vision, scent (imprecise, 30 ft)', speed:'35 ft',
    atk:[['Jaws','1d8','P',[]],['Claw','1d6','S',['agile']]], support:'Each time you hit a foe in its reach, the bear adds 1d8 slashing damage.', man:'Bear Hug', s:'Player Core'},
  {id:'bird', n:'Bird', size:'Small', hp:4, m:[2,3,1,-4,2,0], skill:'Stealth', senses:'Low-light vision', speed:'10 ft, fly 60 ft',
    atk:[['Jaws','1d6','P',['finesse']],['Talon','1d4','S',['agile','finesse']]], support:'Foes you damage that it threatens take 1d4 persistent bleed and are dazzled while bleeding.', man:'Flyby Attack', s:'Player Core'},
  {id:'boar', n:'Boar', size:'Small', hp:8, m:[3,1,2,-4,2,0], skill:'Survival', senses:'Low-light vision, scent (imprecise, 30 ft)', speed:'35 ft',
    atk:[['Tusk','1d8','P',[]]], support:'Foes you damage in its reach take 1d6 persistent bleed.', man:'Boar Charge', s:'Player Core'},
  {id:'cat', n:'Cat', size:'Small', hp:4, m:[2,3,1,-4,2,0], skill:'Stealth', senses:'Low-light vision, scent (imprecise, 30 ft)', speed:'35 ft',
    atk:[['Jaws','1d6','P',['finesse']],['Claw','1d4','S',['agile','finesse']]], support:'Foes you damage in its reach become off-guard until the end of your next turn.', man:'Cat Pounce',
    note:'Deals 1d4 extra precision damage against off-guard targets.', s:'Player Core'},
  {id:'crocodile', n:'Crocodile', size:'Small', hp:6, m:[3,2,2,-4,1,0], skill:'Stealth', senses:'Low-light vision', speed:'20 ft, swim 25 ft',
    atk:[['Jaws','1d8','P',[]],['Tail','1d6','B',['finesse']]], support:'It can latch onto a foe you damage, following it and slowing smaller foes.', man:'Death Roll',
    note:'Can hold its breath for about 2 hours.', s:'Player Core'},
  {id:'dromaeosaur', n:'Dromaeosaur', size:'Small', hp:6, m:[2,3,2,-4,1,0], skill:'Stealth', senses:'Low-light vision, scent (imprecise, 30 ft)', speed:'50 ft',
    atk:[['Jaws','1d8','P',['finesse']],['Talon','1d6','S',['agile','finesse']]], support:'It counts as flanking from any empty space within 10 feet.', man:'Darting Attack', s:'Player Core'},
  {id:'horse', n:'Horse', size:'Medium or Large', hp:8, m:[3,2,2,-4,1,0], skill:'Survival', senses:'Low-light vision, scent (imprecise, 30 ft)', speed:'40 ft',
    atk:[['Hoof','1d6','B',['agile']]], support:'While you ride it, moving 10 feet before a melee Strike adds bonus damage.', man:'Gallop', mount:true, s:'Player Core'},
  {id:'snake', n:'Snake', size:'Small', hp:6, m:[3,3,1,-4,1,0], skill:'Stealth', senses:'Low-light vision, scent (imprecise, 30 ft)', speed:'20 ft, climb 20 ft, swim 20 ft',
    atk:[['Jaws','1d8','P',['finesse']]], support:'Its coils hold foes you damage, hampering their reactions.', man:'Constrict', s:'Player Core'},
  {id:'wolf', n:'Wolf', size:'Small', hp:6, m:[2,3,2,-4,1,0], skill:'Survival', senses:'Low-light vision, scent (imprecise, 30 ft)', speed:'40 ft',
    atk:[['Jaws','1d8','P',['finesse']]], support:'Foes you damage in its reach have their Speed reduced as it tears at their legs.', man:'Knockdown', s:'Player Core'},
  {id:'antelope', n:'Antelope', size:'Medium or Large', hp:6, m:[2,3,2,-4,1,0], skill:'Survival', senses:'Low-light vision', speed:'40 ft',
    atk:[['Horns','1d6','P',['finesse']],['Hoof','1d4','B',['agile','finesse']]], support:'While you ride it, foes you damage in its reach take 1d6 persistent bleed.', man:'Bounding Retreat', mount:true, s:'Howl of the Wild'},
  {id:'elk', n:'Elk', size:'Medium or Large', hp:8, m:[3,2,2,-4,1,0], skill:'Intimidation', senses:'Low-light vision', speed:'30 ft',
    atk:[['Antlers','1d8','P',[]],['Hoof','1d6','B',['agile']]], support:'Foes you hit and damage in its reach become frightened 1.', man:'Antler Catapult', mount:true, s:'Howl of the Wild'},
  {id:'flying-squirrel', n:'Flying Squirrel', size:'Small', hp:6, m:[2,3,1,-4,2,0], skill:'Stealth', senses:'Low-light vision, scent (imprecise, 30 ft)', speed:'25 ft, climb 25 ft',
    atk:[['Jaws','1d6','P',['finesse']],['Claw','1d4','S',['agile','finesse']]], support:'Foes you damage in its reach take −10 feet to their Speeds for a round.', man:'Death From Above',
    note:'Glides when it falls.', s:'Howl of the Wild'},
  {id:'kangaroo', n:'Kangaroo', size:'Small', hp:6, m:[3,2,2,-4,1,0], skill:'Survival', senses:'Low-light vision', speed:'30 ft',
    atk:[['Foot','1d6','B',['agile']]], support:'It counts as flanking from any empty space within 5 feet.', man:'Spring Kick',
    note:'Leaps up to 25 feet horizontally.', s:'Howl of the Wild'},
  {id:'mole', n:'Mole', size:'Small', hp:8, m:[3,2,2,-4,1,0], skill:'Stealth', senses:'Low-light vision, scent (imprecise, 30 ft)', speed:'25 ft, burrow 20 ft',
    atk:[['Jaws','1d8','P',[]],['Claw','1d6','S',['agile']]], support:'Foes you damage next to it become clumsy 1 until they move.', man:'Burrowing Ambush', s:'Howl of the Wild'},
  {id:'mongoose', n:'Mongoose', size:'Small', hp:4, m:[2,3,1,-4,1,1], skill:'Survival', senses:'Low-light vision, scent (imprecise, 30 ft)', speed:'25 ft, burrow 10 ft',
    atk:[['Jaws','1d6','P',['finesse']],['Claw','1d4','S',['agile','finesse']]], support:'Creatures next to it can’t flank you.', man:'Liberating Bite', s:'Howl of the Wild'}
];

const FAMILIAR_ABILITIES = [
  {id:'amphibious', n:'Amphibious', kind:'f', d:'It can breathe underwater and gains a swim Speed of 25 feet (or a land Speed if it already swims).'},
  {id:'burrower', n:'Burrower', kind:'f', d:'It gains a burrow Speed of 5 feet, enough to dig Tiny holes.'},
  {id:'climber', n:'Climber', kind:'f', d:'It gains a climb Speed of 25 feet.'},
  {id:'damage-avoidance', n:'Damage Avoidance', kind:'f', d:'Choose Fortitude, Reflex or Will; when a success on that save would halve damage, it takes none.'},
  {id:'darkvision', n:'Darkvision', kind:'f', d:'It sees in darkness as well as in light.'},
  {id:'fast-movement', n:'Fast Movement', kind:'f', d:'One of its Speeds increases from 25 to 40 feet.'},
  {id:'flier', n:'Flier', kind:'f', d:'It gains a fly Speed of 25 feet.'},
  {id:'kinspeech', n:'Kinspeech', kind:'f', d:'It can talk with animals of its own kind.'},
  {id:'manual-dexterity', n:'Manual Dexterity', kind:'f', d:'It can use up to two limbs to manipulate objects.'},
  {id:'resistance', n:'Resistance', kind:'f', d:'Choose two damage types; it resists them equal to half your level.'},
  {id:'scent', n:'Scent', kind:'f', d:'It gains imprecise scent out to 30 feet.'},
  {id:'skilled', n:'Skilled', kind:'f', d:'Choose a skill other than Acrobatics or Stealth; it uses your level plus your spellcasting attribute for it.'},
  {id:'speech', n:'Speech', kind:'f', d:'It understands and speaks one language you know.'},
  {id:'tough', n:'Tough', kind:'f', d:'Its maximum Hit Points increase by 2 per level.'},
  {id:'cantrip-connection', n:'Cantrip Connection', kind:'m', d:'You can prepare or add one extra cantrip.'},
  {id:'familiar-focus', n:'Familiar Focus', kind:'m', d:'Once per day, your familiar can help you regain a Focus Point.'},
  {id:'lifelink', n:'Lifelink', kind:'m', d:'You can take damage in your familiar’s place to keep it alive.'},
  {id:'spell-battery', n:'Spell Battery', kind:'m', d:'You gain an extra spell slot at least 3 ranks below your highest.'},
  {id:'spell-delivery', n:'Spell Delivery', kind:'m', d:'Your familiar can carry a touch spell to a target for you.'}
];
