const ANC_DESC = {
  dwarf:'Stout, steadfast people of the mountain holds, known for craft, endurance and long memories.',
  elf:'Long-lived and graceful, elves are attuned to magic and to the slow turning of the world.',
  gnome:'Fey-touched wanderers who crave novelty; curious, bright and endlessly inventive.',
  goblin:'Scrappy, quick-witted survivors who meet the world with fire, song and a big appetite.',
  halfling:'Small, nimble and lucky; halflings fit into any community and notice what others miss.',
  human:'Ambitious and adaptable, humans are found everywhere and can excel at nearly anything.',
  leshy:'Plant spirits given living bodies, bound to nature and curious about mortal life.',
  orc:'Hardy and fierce, orcs prize strength of spirit and carry the scars of a long history.',
  anadi:'Reclusive spider people of the Mwangi who can shift between a humanoid and an arachnid form.',
  android:'Synthetic people from Numeria with nanite-laced bodies and muted emotions.',
  athamaru:'Fish-like people of reefs and rivers who share a deep communal bond.',
  automaton:'Constructed bodies that house living souls, built by an ancient empire.',
  'awakened-animal':'Ordinary animals given sapience by magic, fate or the land itself.',
  azarketi:'Amphibious descendants of an ancient sea-dwelling civilization.',
  catfolk:'Agile, curious feline people who love stories, travel and good luck.',
  centaur:'Fleet, sturdy people with a humanoid torso and a horse’s body, tied to land and tradition.',
  conrasu:'Spirits encased in shells of living wood, devoted to cosmic balance.',
  dragonet:'Small draconic creatures, clever and curious, often mistaken for young dragons.',
  fetchling:'Shadow-touched people descended from those who settled the Netherworld.',
  fleshwarp:'People reshaped by magic, alchemy or strange forces, who make their own way.',
  ghoran:'Plant people reborn from seeds, carrying echoes of their past lives.',
  goloma:'Shy, many-eyed people of the Mwangi who are slow to trust strangers.',
  hobgoblin:'Disciplined, organized people with a strong martial tradition.',
  jotunborn:'Descendants of giants, towering and steeped in the lore of their forebears.',
  kashrishi:'Horned, telepathic people who prefer quiet empathy over speech.',
  kholo:'Hyena people who value family, laughter and hard-headed practicality.',
  kitsune:'Fox people who can wear a human-seeming form and love art and trickery.',
  kobold:'Small, crafty draconic people known for traps, tunnels and loyal clans.',
  lizardfolk:'Patient, practical reptilian people with long memories and natural armor.',
  merfolk:'Aquatic people with fish tails, graceful in water and limited on land.',
  minotaur:'Powerful bull-headed people with an uncanny sense of direction.',
  nagaji:'Serpentine people created by nagas, fiercely loyal and hard to poison.',
  poppet:'Dolls and figures brought to life by love, purpose or stray magic.',
  ratfolk:'Clever, communal rat people with a knack for trade and tinkering.',
  samsaran:'Blue-skinned people who reincarnate and remember fragments of past lives.',
  sarangay:'Strong, buffalo-horned people who prize the gems grown in their horns.',
  shisk:'Quill-covered keepers of knowledge from deep caverns.',
  shoony:'Small, humble dog people known for farming, loyalty and hard work.',
  skeleton:'Undead skeletons that kept their free will and walk among the living.',
  sprite:'Tiny fey with luminous auras and boundless mischief.',
  strix:'Winged, fiercely territorial people who rule the high places.',
  surki:'Insect-like people from the depths who absorb magic to evolve their bodies.',
  tanuki:'Jovial raccoon-dog shapeshifters of Tian Xia who love a good prank.',
  tengu:'Crow-like people, scavengers and collectors with sharp beaks and sharper wits.',
  tripkee:'Small tree frog people, agile climbers and keen survivalists.',
  vanara:'Monkey people of Vudra with prehensile tails and lively curiosity.',
  vishkanya:'Serpent-blooded people who can draw venom from their own bodies.',
  wayang:'Small shadow-touched people who left the Netherworld seeking light and new lives.',
  yaksha:'Nature spirits in mortal form who guard the wild and uphold moral duty.',
  yaoguai:'Beings that awakened from objects, animals or spirits by absorbing vital energy.'
};
const VH_DESC = {
  aiuvarin:'Part elf: you count as an elf for feats and gain low-light vision.',
  dromaar:'Part orc: you count as an orc for feats and gain low-light vision.',
  changeling:'Child of a hag, with mismatched eyes and a pull toward the occult.',
  dhampir:'Child of a vampire, living but touched by undeath.',
  nephilim:'Descended from celestial, fiendish or monitor beings.',
  duskwalker:'A psychopomp soul reborn into flesh, foe of the undead.',
  beastkin:'You can shift between your usual form and a hybrid animal shape.',
  reflection:'A duplicate of another person, created by magic and now your own.',
  dragonblood:'Draconic blood shows in your scales, eyes or temper.',
  hungerseed:'Descended from oni, with horns and a great appetite.',
  talos:'Metal elemental heritage.', suli:'Heritage touched by the balance of several elements.',
  naari:'Fire elemental heritage.', sylph:'Air elemental heritage.', undine:'Water elemental heritage.',
  oread:'Earth elemental heritage.', ardande:'Wood elemental heritage.'
};
const CLS_DESC = {
  alchemist:'A crafter of bombs, elixirs and mutagens powered by alchemical reagents.',
  animist:'A spiritual intermediary who channels apparitions to cast divine spells.',
  barbarian:'A furious warrior who turns rage into raw power and staying power.',
  bard:'A performer whose art carries occult magic and lifts up allies.',
  champion:'A holy or unholy warrior sworn to a deity and to protecting allies.',
  cleric:'A devoted servant of a deity who channels divine magic.',
  commander:'A tactician who directs allies with drilled tactics and battlefield orders.',
  druid:'A guardian of the natural world who calls on primal magic.',
  exemplar:'A mortal with a spark of divinity, channelled through sacred ikons.',
  fighter:'A master of weapons and armor with unmatched accuracy.',
  guardian:'A heavily armored protector who draws enemies’ attention away from allies.',
  gunslinger:'A specialist in firearms and crossbows with signature deeds.',
  inventor:'A tinkerer who builds, overdrives and occasionally explodes a unique innovation.',
  investigator:'A sharp-minded sleuth who plans strikes through clever stratagems.',
  kineticist:'A conduit of elemental power who channels impulses through a kinetic gate.',
  magus:'A warrior-scholar who channels spells through weapon strikes.',
  monk:'A disciplined martial artist who fights with body and focus.',
  necromancer:'A caster who raises and commands thralls drawn from death’s power.',
  oracle:'A divine caster both empowered and burdened by a mystery.',
  psychic:'A caster whose mind unleashes occult power through sheer will.',
  ranger:'A tracker and hunter who marks prey and strikes with precision.',
  rogue:'A skilled opportunist who strikes where enemies are weakest.',
  runesmith:'A crafter who etches and invokes magical runes in battle.',
  sorcerer:'A spellcaster with magic running in their blood.',
  summoner:'A caster bonded to an eidolon that fights at their side.',
  swashbuckler:'A daring duelist who builds panache with flair to unleash finishers.',
  thaumaturge:'A monster hunter who exploits weaknesses with implements and esoterica.',
  witch:'A spellcaster who receives magic from a mysterious patron through a familiar.',
  wizard:'A scholar who masters arcane magic through study and a spellbook.'
};
const FEATURE_DESC = {
  'Rage':'Gain temporary Hit Points and extra melee damage for a minute.',
  'Instinct':'The source of your fury, which shapes your rage.',
  'Reactive Strike':'Strike a creature that lowers its guard within your reach.',
  'Shield Block':'Reduce damage with a raised shield.',
  'Sneak Attack':'Extra precision damage against off-guard foes.',
  'Surprise Attack':'Foes who haven’t acted yet are off-guard to you.',
  'Flurry of Blows':'Make two unarmed Strikes for one action.',
  'Powerful Fist':'Your fists hit harder and aren’t penalized for lethal damage.',
  'Hunt Prey':'Mark a creature as your prey for bonuses against it.',
  'Arcane Bond':'Recall a spell you already cast once per day.',
  'Divine Font':'Extra healing or harming spells each day.',
  'Familiar':'A magical companion that aids your magic.'
};
const SUB_DESC = {
  bomber:'Specialize in alchemical bombs and controlling their splash.', chirurgeon:'Healing elixirs and medical alchemy; Crafting can stand in for Medicine.',
  mutagenist:'Transform your own body with mutagens.', toxicologist:'Brew and apply poisons to your weapons.',
  liturgist:'Channel apparitions through dance and ritual to empower allies.', medium:'Swap apparitions on the fly and let them guide you.',
  seer:'Sense the spirit world and gain extra insight from apparitions.', shaman:'Commune closely with a bonded apparition for stronger effects.',
  'animal-instinct':'Your rage awakens a beast within, granting natural attacks.', bloodrager:'Arcane magic surges through your rage.',
  'decay-instinct':'Your fury brings rot and entropy.', 'dragon-instinct':'Channel the might of a chosen dragon.',
  'elemental-instinct':'Rage with the power of an element.', 'fury-instinct':'Pure anger with no outside source; gain an extra feat.',
  'giant-instinct':'Wield oversized weapons for heavy damage.', 'ligneous-instinct':'Rage with the patient strength of the forest.',
  'spirit-instinct':'Ancestral or other spirits fuel your rage.', 'superstition-instinct':'Your rage resists magic of every kind.',
  enigma:'You seek hidden truths and gain Bardic Lore.', maestro:'Pure musical mastery; gain Lingering Composition.',
  polymath:'A dabbler in everything; gain Versatile Performance.', warrior:'Songs of battle; gain Martial Performance.',
  zoophonia:'Your music speaks to animals and earns you a companion’s trust.',
  grandeur:'Holy cause of inspiring awe and protecting the faithful.', justice:'Holy cause of punishing those who harm your allies.',
  liberation:'Holy cause of freeing allies from restraint.', obedience:'Unholy cause of order through domination.',
  redemption:'Holy cause of giving foes a chance to turn from harm.',
  'battle-creed':'A martial devotee trained with your deity’s weapon.', 'cloistered-cleric':'Devoted to spellcasting; gain a domain spell.',
  warpriest:'Armored faith with shield training and a sturdier body.',
  'animal-order':'Bond with an animal companion.', 'cultivation-order':'Nurture plants and growth.', 'flame-order':'Command fire and heat.',
  'leaf-order':'Tend growing things with a leshy familiar.', 'spore-order':'Embrace fungi, decay and renewal.', 'stone-order':'Draw strength from earth and stone.',
  'storm-order':'Call wind and lightning.', 'untamed-order':'Take on the shapes of wild beasts.', 'wave-order':'Command water and tides.',
  'bands-of-imprisonment':'Worn bands that bind and resist foes.', 'barrow-s-edge':'A blade that thirsts for wounded foes.', 'eye-catching-spot':'A divine mark that draws attention.',
  'fetching-bangles':'Bangles that pull foes or objects toward you.', 'gaze-sharp-as-steel':'Eyes that spot danger before it lands.', 'gleaming-blade':'A shining weapon that strikes swiftly.',
  'hands-of-the-wildling':'Hands that rend like claws.', 'horn-of-plenty':'A vessel that sustains and restores.', 'mirrored-aegis':'A shield that reflects and protects.',
  'mortal-harvest':'A reaping weapon that cuts down the fallen.', 'noble-branch':'A spear or polearm of noble reach.', 'pelt-of-the-beast':'A hide that shields against the elements.',
  'scar-of-the-survivor':'A scar that hardens you against harm.', 'shadow-sheath':'Hidden blades that strike from concealment.', 'skin-hard-as-horn':'Skin that turns aside blows.',
  'skybearer-s-belt':'A belt that grants titanic strength.', starshot:'A ranged weapon that shoots like a falling star.', 'thousand-league-sandals':'Sandals that carry you swiftly.',
  'titan-s-breaker':'A heavy weapon that shatters defenses.', 'unfailing-bow':'A bow whose shots fly true.', 'victor-s-wreath':'A crown that rallies allies.',
  'way-of-the-drifter':'Mix a firearm with a melee weapon as a wandering duelist.', 'way-of-the-pistolero':'Quick-draw showmanship with one-handed firearms.',
  'way-of-the-sniper':'Patient, hidden shots from long range.', 'way-of-the-triggerbrand':'Combination weapons that switch between gun and blade.', 'way-of-the-vanguard':'Heavy firearms on the front line.',
  'armor-innovation':'Your invention is a suit of modified armor.', 'construct-innovation':'Your invention is a construct companion.',
  'light-mortar-innovation':'Your invention is a deployable siege mortar.', 'weapon-innovation':'Your invention is a modified weapon.',
  'alchemical-sciences-methodology':'Investigate with alchemy and quick elixirs.', 'empiricism-methodology':'Deduce through keen observation and logic.',
  'forensic-medicine-methodology':'Read clues from bodies and wounds; skilled at healing.', 'interrogation-methodology':'Pry truth from people through conversation.',
  'palatine-detective':'A Palatine Eye agent who studies the occult.',
  'air-gate':'Channel wind, lightning and sky.', 'earth-gate':'Channel stone, sand and metal ore.', 'fire-gate':'Channel flame, heat and light.',
  'metal-gate':'Channel shaped metal and magnetism.', 'water-gate':'Channel water, ice and currents.', 'wood-gate':'Channel plants, growth and life.',
  'inexorable-iron':'Heavy two-handed weapons that crush foes.', 'laughing-shadow':'Mobile, quick strikes with dimensional steps.', 'sparkling-targe':'Fight with a shield and spells together.',
  'starlit-span':'Deliver spellstrikes with ranged weapons.', 'twisting-tree':'Fight with a staff that shifts between reach and power.', 'twofold-tine':'Two weapons striking as one.',
  puppeteer:'Control thralls with precision from a distance.', reaper:'Fight alongside thralls in close combat.',
  blood:'Draw on blood and vitality.', bone:'Command bones and skeletal power.', flesh:'Shape and animate flesh.', spirit:'Command restless spirits.',
  ancestors:'Voices of the dead guide and haunt you.', ashes:'Fire and rebirth from destruction.', battle:'The glory and toll of war.',
  blight:'Decay and disease made into power.', bones:'Death and the boundary of life.', cosmos:'The stars and celestial weight.',
  flames:'Burning power that consumes you too.', life:'Healing and vitality at your own expense.', lore:'Hidden knowledge that overwhelms the mind.',
  tempest:'Wind, water and the fury of storms.', time:'Glimpses of past and future.',
  'the-distant-grasp':'Telekinetic power to move things with your mind.', 'the-infinite-eye':'Clairvoyant sight across distance and minds.',
  'the-oscillating-wave':'Shift energy between fire and cold.', 'the-silent-whisper':'Telepathy and mental assault.',
  'the-tangible-dream':'Shape thoughts into solid forms.', 'the-unbound-step':'Teleportation and swift movement.',
  'emotional-acceptance':'Power from embracing your emotions; Charisma key.', 'gathered-lore':'Power from accumulated study; Intelligence key.',
  'precise-discipline':'Power from rigorous mental control; Intelligence key.', 'wandering-reverie':'Power from daydreams and wonder; Charisma key.',
  flurry:'A smaller multiple attack penalty against your prey.', outwit:'Bonuses to skills and AC against your prey.',
  precision:'Extra precision damage on your first hit each round against your prey.', vindicator:'Swear vengeance on prey that harmed others.',
  avenger:'Strike in your deity’s name with religious training.', 'eldritch-trickster':'Blend arcane tricks with rogue skills; gain a multiclass dedication.',
  mastermind:'Recall Knowledge to catch foes off guard.', ruffian:'Brute force, bigger sneak attack weapons and medium armor.',
  scoundrel:'Feint and charm your way through fights.', thief:'Add Dexterity to damage with finesse melee weapons.',
  'bloodline-aberrant':'Strange occult power from beyond.', 'bloodline-aesir':'Divine might of northern gods.', 'bloodline-angelic':'Celestial grace and healing.',
  'bloodline-demonic':'Abyssal fury and corruption.', 'bloodline-diabolic':'Infernal fire and contracts.', 'bloodline-draconic':'The might and breath of dragons.',
  'bloodline-elemental':'Raw power of an element.', 'bloodline-fey':'Charm and illusion of the First World.', 'bloodline-genie':'Wish-granting genie heritage.',
  'bloodline-hag':'Cruel hag magic and curses.', 'bloodline-harrow':'Fate read through harrow cards.', 'bloodline-imperial':'Ancient arcane mastery of empires.',
  'bloodline-nymph':'Natural beauty and emotional magic.', 'bloodline-psychopomp':'Guardians of souls between life and death.', 'bloodline-shadow':'Darkness and the Netherworld.',
  'bloodline-undead':'Death’s touch in your blood.', 'bloodline-wyrmblessed':'Divine power of a dragon god.',
  'aberrant-eidolon':'A strange, otherworldly partner.', 'angel-eidolon':'A celestial guardian.', 'anger-phantom-eidolon':'A wrathful spirit.', 'beast-eidolon':'A primal animal spirit.',
  'construct-eidolon':'A crafted, mechanical partner.', 'demon-eidolon':'A sinful fiend bound to you.', 'devotion-phantom-eidolon':'A loyal, protective spirit.',
  'dragon-eidolon':'A draconic partner with a breath weapon.', 'elemental-eidolon':'A living element.', 'fey-eidolon':'A capricious fey spirit.',
  'ooze-eidolon':'A shapeless, absorbing ooze.', 'plant-eidolon':'A living plant.', 'psychopomp-eidolon':'A guide of souls.', 'swarm-eidolon':'A swarm of small creatures.', 'undead-eidolon':'A loyal undead partner.',
  battledancer:'Gain panache through dazzling performance.', braggart:'Gain panache by demoralizing foes.', fencer:'Gain panache by feinting.',
  gymnast:'Gain panache with grapples, trips and shoves.', rascal:'Gain panache through dirty tricks.', wit:'Gain panache with banter and Bon Mot.',
  amulet:'A protective charm that shields allies.', bell:'A bell whose ring disrupts foes.', chalice:'A vessel that heals and invigorates.',
  lantern:'A light that reveals the hidden.', mirror:'A mirror that lets you be in two places.', regalia:'Symbols of authority that inspire.',
  shield:'A shield implement that blocks magic and blows.', tome:'A book of esoteric knowledge.', wand:'A wand that unleashes blasts.', weapon:'A weapon implement for decisive strikes.',
  'choir-politic':'Divine patron of community and consensus.', 'devourer-of-decay':'Primal patron of rot and renewal.', 'faith-s-flamekeeper':'Divine patron of conviction.',
  'paradox-of-opposites':'Divine patron of balance between extremes.', 'ripple-in-the-deep':'Primal patron of hidden depths.', 'silence-in-snow':'Primal patron of winter.',
  'spinner-of-threads':'Occult patron of fate.', 'starless-shadow':'Occult patron of night.', 'the-inscribed-one':'Arcane patron of written lore.',
  'the-resentment':'Occult patron of grudges.', 'the-unseen-broker':'Occult patron of secret deals.', 'whisper-of-wings':'Primal patron of flight and messages.', 'wilding-steward':'Primal patron of the wild.',
  'school-of-ars-grammatica':'The fundamental language of magic itself.', 'school-of-battle-magic':'Spells honed for the battlefield.', 'school-of-civic-wizardry':'Practical magic for building and community.',
  'school-of-keen-inquiry':'Divination and uncovering truths.', 'school-of-mentalism':'Magic of the mind and perception.', 'school-of-nexian-spaces':'Teleportation and space.',
  'school-of-protean-form':'Transformation and change.', 'school-of-quantic-control':'Probability and fate.', 'school-of-unified-magical-theory':'No school; gain an extra wizard feat.',
  'school-of-the-boundary':'The edges between life, death and planes.',
  'experimental-spellshaping':'Gain a spellshape feat and change it daily.', 'improved-familiar-attunement':'A stronger familiar that grows with you.',
  'spell-blending':'Trade lower slots for higher-rank ones.', 'spell-substitution':'Swap prepared spells in 10 minutes.', 'staff-nexus':'Your bonded staff holds extra spells.'
};
const TRAIT = {
  agile:'Your multiple attack penalty with it is −4 and −8 instead of −5 and −10.',
  finesse:'You can use Dexterity instead of Strength on attack rolls.',
  deadly:'On a critical hit, add one extra weapon damage die of the listed size.',
  fatal:'On a critical hit, the damage die grows to the listed size and you add one more die.',
  forceful:'Deals extra damage on your second and later attacks with it each turn.',
  sweep:'+1 to attack a target other than one you already attacked this turn.',
  reach:'You can attack creatures 10 feet away instead of 5.',
  thrown:'You can throw it as a ranged attack and add Strength to damage.',
  propulsive:'Add half your Strength modifier (if positive) to damage.',
  volley:'−2 to attack targets within the listed distance.',
  versatile:'Can deal the listed damage type instead of its usual one.',
  'two-hand':'Held in two hands, its damage die becomes the listed size.',
  backstabber:'Extra precision damage against off-guard targets.',
  backswing:'After a miss, +1 to your next attack with it this turn.',
  disarm:'You can use it to Disarm with Athletics.', trip:'You can use it to Trip with Athletics.',
  shove:'You can use it to Shove with Athletics.', grapple:'You can use it to Grapple with Athletics.',
  nonlethal:'Attacks with it are nonlethal.', parry:'Spend an action to gain +1 AC until your next turn.',
  twin:'Extra damage when you attack with two of these weapons in a turn.', 'free-hand':'It doesn’t occupy your hand.',
  monk:'Works with monk abilities such as Flurry of Blows.', unarmed:'An unarmed attack.',
  concussive:'Uses the lower of the target’s bludgeoning or piercing resistance.',
  concealable:'Easy to hide on your body.', modular:'Can switch between damage types with an action.',
  'ranged-trip':'You can Trip at range with it.', tethered:'Tied to a line so you can pull it back after throwing.',
  kickback:'Powerful recoil: −2 to attack unless you have Strength +1 or a brace.',
  scatter:'Deals splash damage in the listed radius.', capacity:'Holds several shots before reloading.',
  repeating:'Fires repeatedly from a magazine.', brace:'Extra damage against a creature that moves toward you.',
  razing:'Extra damage against objects and constructs.', combination:'A melee weapon combined with a firearm.',
  splash:'Deals splash damage to the target and adjacent creatures, even on a miss.',
  bomb:'An alchemical explosive thrown as a ranged attack.',
  flexible:'The armor’s check penalty doesn’t apply to Acrobatics or Athletics.',
  noisy:'The check penalty applies to Stealth even if you meet the Strength requirement.',
  bulwark:'Use +3 instead of Dexterity on Reflex saves against damaging effects.',
  comfort:'You can sleep in it without becoming fatigued.',
  laminar:'Resists damage that would make the armor brittle.', ponderous:'Your initiative is slowed by its bulk.',
  'attached-to-shield':'Attached to a shield and used with it.',
  consumable:'Used up when activated.', alchemical:'Made through alchemy rather than magic.',
  magical:'Infused with magic.', elixir:'An alchemical liquid you drink.', potion:'A magical liquid you drink.',
  healing:'Restores Hit Points or removes harm.', invested:'You must invest it to use its magic (limit of 10 per day).',
  poison:'Inflicts or relates to poison.', injury:'A poison delivered through a wound.',
  ingested:'A poison delivered by eating or drinking.', contact:'A poison delivered by touch.',
  inhaled:'A poison delivered by breathing it in.', talisman:'A one-use magic item you affix to armor or a weapon.',
  oil:'A magical substance you apply to an object or creature.', scroll:'A one-use spell you can read if you have the tradition.',
  attack:'Uses an attack roll, so multiple attack penalty applies.', concentrate:'Requires mental focus.',
  manipulate:'Requires gesturing or handling; can trigger reactions.', mental:'Affects the mind; mindless creatures are immune.',
  emotion:'Affects emotions.', fear:'Plays on fear.', auditory:'Relies on sound.', visual:'Relies on sight.',
  linguistic:'Relies on language; creatures that don’t understand are unaffected.',
  incapacitation:'Weaker against creatures of higher level than you.', sustained:'You must Sustain it each turn to keep it going.',
  illusion:'Creates false sensations.', light:'Creates light.', darkness:'Creates darkness.',
  fire:'Fire damage or effects.', cold:'Cold damage or effects.', acid:'Acid damage or effects.', electricity:'Electricity damage or effects.',
  sonic:'Sonic damage or effects.', force:'Force damage or effects.', vitality:'Living energy that heals the living and harms undead.',
  void:'Negative energy that harms the living and heals undead.', spirit:'Damages a creature’s spirit.',
  fortune:'Lets you roll twice and take the better result; you can’t stack fortune effects.',
  misfortune:'Makes you roll twice and take the worse result.',
  flourish:'You can use only one flourish action per turn.', press:'Only usable while you already have a multiple attack penalty.',
  open:'Only usable as your first attack action of the turn.', stance:'A fighting stance that lasts until you leave it.',
  rage:'Only usable while raging.', general:'A general feat anyone can take.', skill:'A skill feat tied to a skill.',
  secret:'The GM rolls for you.', exploration:'Used during exploration, outside encounters.', downtime:'Used during downtime.',
  uncommon:'Requires GM permission, a special background or specific circumstances to access.',
  rare:'Very hard to find; usually only available with GM permission.', unique:'One of a kind.',
  lineage:'A heritage-defining feat; you can take only one lineage feat.',
  dedication:'Starts an archetype.', cantrip:'A spell you can cast at will.'
};

const CLASS_EXTRA = {
  fighter:{grp:['Acrobatics','Athletics']}, monk:{grp:['Acrobatics','Athletics']},
  champion:{deity:1}, cleric:{deity:1}, psychic:{key:['int','cha']}
};
const SUB_OVR = {
  ruffian:{def:{medium:1},key:['str']}, mastermind:{key:['int']}, scoundrel:{key:['cha']}, thief:{thief:1},
  avenger:{def:{medium:1}}, warpriest:{def:{light:1,medium:1},saves:{fort:2},grants:['Shield Block']}
};
const HER_OVR = {'skilled-human':{freeSkill:1}, 'nomadic-halfling':{langs:2}, 'versatile-human':{genFeat:1}};
const TRAD = {bard:'occult',cleric:'divine',druid:'primal',oracle:'divine',psychic:'occult',wizard:'arcane',magus:'arcane',animist:'divine',necromancer:'occult',champion:'divine'};
const SLOT_CASTERS = ['animist','bard','cleric','druid','magus','necromancer','oracle','psychic','sorcerer','summoner','witch','wizard'];
const SPELL_GUIDE = {bard:[5,2,'repertoire'],sorcerer:[5,3,'repertoire'],oracle:[5,2,'repertoire'],cleric:[5,2,'prepared'],druid:[5,2,'prepared'],wizard:[10,5,'spellbook'],witch:[10,5,'familiar']};
